services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 8080:80
    restart: always
    depends_on:
      - database
    env_file:
      - ./.env
    networks:
      - local